# Form implementation generated from reading ui file 'QRCode6.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 500)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_QRCode = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_QRCode.sizePolicy().hasHeightForWidth())
        self.groupBox_QRCode.setSizePolicy(sizePolicy)
        self.groupBox_QRCode.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_QRCode.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_QRCode.setObjectName("groupBox_QRCode")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_QRCode)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_qrCode = QtWidgets.QGridLayout()
        self.gridLayout_qrCode.setObjectName("gridLayout_qrCode")
        self.gridLayout.addLayout(self.gridLayout_qrCode, 1, 0, 1, 1)
        self.pushButton_export = QtWidgets.QPushButton(parent=self.groupBox_QRCode)
        self.pushButton_export.setObjectName("pushButton_export")
        self.gridLayout.addWidget(self.pushButton_export, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_QRCode, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_json = QtWidgets.QWidget()
        self.tab_json.setObjectName("tab_json")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_json)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEdit_JSON = QtWidgets.QTextEdit(parent=self.tab_json)
        self.textEdit_JSON.setStyleSheet("font: 57 14pt \"Gotham\";")
        self.textEdit_JSON.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.textEdit_JSON.setProperty("tabStopWidth", 40)
        self.textEdit_JSON.setObjectName("textEdit_JSON")
        self.gridLayout_3.addWidget(self.textEdit_JSON, 0, 0, 1, 1)
        self.label_JSON_state = QtWidgets.QLabel(parent=self.tab_json)
        self.label_JSON_state.setObjectName("label_JSON_state")
        self.gridLayout_3.addWidget(self.label_JSON_state, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_json, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.plainTextEdit_string = QtWidgets.QPlainTextEdit(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_string.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_string.setSizePolicy(sizePolicy)
        self.plainTextEdit_string.setStyleSheet("font: 57 14pt \"Gotham\";")
        self.plainTextEdit_string.setObjectName("plainTextEdit_string")
        self.gridLayout_4.addWidget(self.plainTextEdit_string, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionWebSockt = QtGui.QAction(parent=MainWindow)
        self.actionWebSockt.setObjectName("actionWebSockt")
        self.actionSocket = QtGui.QAction(parent=MainWindow)
        self.actionSocket.setObjectName("actionSocket")
        self.actionAPIs = QtGui.QAction(parent=MainWindow)
        self.actionAPIs.setObjectName("actionAPIs")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QR Code Generator"))
        self.groupBox_QRCode.setTitle(_translate("MainWindow", "QR Code"))
        self.pushButton_export.setText(_translate("MainWindow", "Export"))
        self.label_JSON_state.setText(_translate("MainWindow", "The JSON is not valid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_json), _translate("MainWindow", "JSON"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "String"))
        self.actionWebSockt.setText(_translate("MainWindow", "WebSocket"))
        self.actionSocket.setText(_translate("MainWindow", "Socket"))
        self.actionAPIs.setText(_translate("MainWindow", "APIs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
